// Problem #2 from ProjectEuler.net archives

/* Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms. */

#include <stdio.h>

main()
{

    int a = 0;
    int b = 0;
    int c = 0;
    int sum = 0;

    for (int i = 1; i <= 4000000; i = c)
    {
        //create the Fibonacci sequence
        b = i;
        c = a + b;
        a = b;

        //add term to sum if even
        if (c % 2 == 0)
        {
            printf("\n%d", c);
            sum = sum + c;
        }
    }

    // The starting point for i (2) was not included. Add this
    // manually to the sum.
    // sum = sum + 2;
    printf("\n\nThe sum is: %d\n\n", sum);

    return 0;
}
